[build]
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"

# 2013 Posts Redirects
[[redirects]]
  from = "/Marathon-Epilogue"
  to = "/posts/2013/a-marathon-in-three-parts-epilogue"

[[redirects]]
  from = "/Marathon-First-Goal"
  to = "/posts/2013/a-marathon-in-three-parts-the-first-goal"

[[redirects]]
  from = "/Marathon-Second-Goal"
  to = "/posts/2013/a-marathon-in-three-parts-goal-number-two"

[[redirects]]
  from = "/Marathon-Third-Goal"
  to = "/posts/2013/a-marathon-in-three-parts-goal-the-third"

# 2014 Posts Redirects
[[redirects]]
  from = "/300-Rise-Of-An-Empire"
  to = "/posts/2014/300-rise-of-an-empire-of-freedom-for-free-greeks"

[[redirects]]
  from = "/A-Month-With-Divvy"
  to = "/posts/2014/a-month-with-divvy"

[[redirects]]
  from = "/All-I-Wanted-Was-An-Integer-Primary-Key"
  to = "/posts/2014/all-i-wanted-was-an-integer-primary-key"

[[redirects]]
  from = "/April-2014-Arizona-Trip"
  to = "/posts/2014/april-2014-arizona-trip"

[[redirects]]
  from = "/Being-Online"
  to = "/posts/2014/being-online"

[[redirects]]
  from = "/Data-Layers-Reducing-Repetition"
  to = "/posts/2014/data-layers-and-finding-ways-  to-reduce-repetition"

[[redirects]]
  from = "/Divvy-Is-Delightful"
  to = "/posts/2014/divvy-is-delightful"

[[redirects]]
  from = "/Establishing-Knockoutjs-Design-Patterns"
  to = "/posts/2014/establishing-knockout-js-design-patterns"

[[redirects]]
  from = "/Exactly-One-Hobby"
  to = "/posts/2014/exactly-one-hobby"

[[redirects]]
  from = "/False-Errors-and-Silent-Failures"
  to = "/posts/2014/false-errors-are-better-than-silent-failures"

[[redirects]]
  from = "/Hills-In-Chicago"
  to = "/posts/2014/hills-in-chicago"

[[redirects]]
  from = "/I-Need-A-New-Backpack"
  to = "/posts/2014/i-need-a-new-backpack"

[[redirects]]
  from = "/Knockoutjs-Tu  torials-Suck"
  to = "/posts/2014/knockout-js-tu  torials-suck-but-not-as-much-as-the-documentation"

[[redirects]]
  from = "/MS-Stack-Is-Not-Closed-Source"
  to = "/posts/2014/just-because-it-s-on-the-microsoft-stack-doesn-t-mean-it-s-closed-source"

[[redirects]]
  from = "/No-Support-For-White-Men"
  to = "/posts/2014/no-support-for-white-men"

[[redirects]]
  from = "/Returning-  to-An-Old-Project"
  to = "/posts/2014/returning-  to-an-old-project"

[[redirects]]
  from = "/Rovani-in-C-sharp"
  to = "/posts/2014/rovani-in-c"

[[redirects]]
  from = "/Ugliest-Week-In-Chicago"
  to = "/posts/2014/the-ugliest-week-in-chicago"

[[redirects]]
  from = "/Value-of-Content"
  to = "/posts/2014/que-sera-sera-the-value-of-content"

# 2015 Posts Redirects
[[redirects]]
  from = "/2015-Wisconsin-Marathon"
  to = "/posts/2015/3-56-58-2015-wisconsin-marathon/"

[[redirects]]
  from = "/Commit-4b684657/"
  to = "/posts/2015/laying-the-foundation/"

[[redirects]]
  from = "/Lets-Do-the-Time-Warp-Again/"
  to = "/posts/2015/let-s-do-the-time-warp-again/"

[[redirects]]
  from = "/Commit-69a7825e/"
  to = "/posts/2015/letting-users-get-ahead-of-me"

[[redirects]]
  from = "/Naming-The-Patron-Object"
  to = "/posts/2015/naming-the-patron-object/"

[[redirects]]
  from = "/Overall-Fitness-In-8-Tests"
  to = "/posts/2015/overall-fitness-in-8-tests/"

[[redirects]]
  from = "/Commit-bccg1aea/"
  to = "/posts/2015/preemptively-structuring-the-chaos/"

[[redirects]]
  from = "/Recurring-Gifts-Database-Schema"
  to = "/posts/2015/recurring-gifts-part-1-database-schema/"

[[redirects]]
  from = "/Commit-8c41b3dc/"
  to = "/posts/2015/vigil-base-solution"

[[redirects]]
  from = "/Commit-527fabb8/"
  to = "/posts/2015/vigil-data-solution-and-initial-projects/"

# 2016 Posts Redirects
[[redirects]]
  from = "/A-Word-On-Fac  tory-Results"
  to = "/posts/2016/a-word-on-fac  tory-results-and-contracts/"

[[redirects]]
  from = "/A-Word-On-Validation"
  to = "/posts/2016/a-word-on-validation/"

[[redirects]]
  from = "/Chicago-Marathon-2016"
  to = "/posts/2016/2016-chicago-marathon-wrap-up/"

[[redirects]]
  from = "/Disneys-Dopey-Challenge"
  to = "/posts/2016/disney-s-dopey-challenge"

[[redirects]]
  from = "/Everything-Gets-An-Id"
  to = "/posts/2016/everything-gets-an-id"

[[redirects]]
  from = "/Hello-World"
  to = "/posts/2016/hello-world/"

[[redirects]]
  from = "/Patron-Can-Be-Created-and-Updated"
  to = "/posts/2016/patron-can-be-created-and-updated-again/"

[[redirects]]
  from = "/Revisiting-Creating-and-Updating-Entities"
  to = "/posts/2016/revisiting-creating-and-updating-entities"

[[redirects]]
  from = "/Stumbling-In  to-Design-Patterns"
  to = "/posts/2016/stumbling-in  to-design-patterns/"

[[redirects]]
  from = "/User-Can-Create-New-Patron"
  to = "/posts/2016/user-can-create-new-patron/"

[[redirects]]
  from = "/User-Can-Update-Patron"
  to = "/posts/2016/user-can-update-a-patron/"

[[redirects]]
  from = "/User-Cannot-Create-Patron-That-Fails-Validation"
  to = "/posts/2016/user-cannot-create-patron-that-fails-validation/"

# 2017 Posts Redirects
[[redirects]]
  from = "/2017-Racing-Calendar"
  to = "/posts/2017/my-2017-running-calendar/"

[[redirects]]
  from = "/2017-Year-in-Review"
  to = "/posts/2017/2017-year-in-review/"

[[redirects]]
  from = "/22-Month-Status-Report"
  to = "/posts/2017/22-month-status-report/"

[[redirects]]
  from = "/Azure-Command-Queue"
  to = "/posts/2017/vigil-s-azure-command-queue/"

[[redirects]]
  from = "/Azure-Machine-Learning"
  to = "/posts/2017/azure-machine-learning-data-camp/"

[[redirects]]
  from = "/Discovering-Core-MVC"
  to = "/posts/2017/2017/discovering-mvc-the-asp-net-core-mvc-stack/"

[[redirects]]
  from = "/Explicit-Model-Construc  tor"
  to = "/posts/2017/using-an-explicit-model-construc  tor-with-a-json-input-formatter/"

[[redirects]]
  from = "/Hydrating-A-Patron"
  to = "/posts/2017/hydrating-a-patron/"

[[redirects]]
  from = "/Illusions-of-Queues-and-Buses"
  to = "/posts/2017/illusions-of-queues-and-buses/"

[[redirects]]
  from = "/Introducing-Vigil-Web-API"
  to = "/posts/2017/introducing-vigil-web-api/"

[[redirects]]
  from = "/Mock-Controller-Url"
  to = "/posts/2017/mock-controller-s-user-and-url-properties-in-asp-net-core-mvc/"

[[redirects]]
  from = "/Tat  too-Number-2"
  to = "/posts/2017/tat  too-number-two/"

[[redirects]]
  from = "/500-Words"
  to = "/posts/2017/what-does-500-words-look-like/"

[[redirects]]
  from = "/Whole30-Day-0"
  to = "/posts/2017/whole30-2017-day-0-buying-the-costco-chicken-farm/"

[[redirects]]
  from = "/Whole30-Day-1"
  to = "/posts/2017/whole30-2017-day-1-take-two/"

[[redirects]]
  from = "/Whole30-Day-5"
  to = "/posts/2017/whole30-2017-day-5-menu-planning-sucks/"

# 2018 Posts Redirects
[[redirects]]
  from = "/30-Burpees-Challenge/"
  to = "/posts/2018/30-burpees-per-day-challenge/"

[[redirects]]
  from = "/AzureADB2C-User-Secrets/"
  to = "/posts/2018/using-azure-ad-b2-c-and-visual-studio-user-secrets/"

[[redirects]]
  from = "/Ninth-Week-Meal-Planning/"
  to = "/posts/2018/february-25-march-4-meal-planning/"

[[redirects]]
  from = "/Hamburger-Experiment"
  to = "/posts/2018/hamburger-and-fries-experiment/"

[[redirects]]
  from = "/I-Made-a-Logo/"
  to = "/posts/2018/i-made-a-logo/"

[[redirects]]
  from = "/First-Week-Meal-Planning/"
  to = "/posts/2018/january-1-7-meal-planning/"

[[redirects]]
  from = "/Fourth-Week-Meal-Planning/"
  to = "/posts/2018/january-21-27-meal-planning/"

[[redirects]]
  from = "/Fifth-Week-Meal-Planning/"
  to = "/posts/2018/january-29-february-4-meal-planning/"

[[redirects]]
  from = "/Second-Week-Meal-Planning/"
  to = "/posts/2018/january-8-14-meal-planning/"

[[redirects]]
  from = "/Twelfth-Week-Meal-Planning/"
  to = "/posts/Twelfth-Week-Meal-Planning/"

[[redirects]]
  from = "/Tenth-Week-Meal-Planning/"
  to = "/posts/2018/march-4-11-meal-planning/"

[[redirects]]
  from = "/My-Time-at-The-Fellowship/"
  to = "/posts/2018/my-time-at-the-fellowship/"

[[redirects]]
  from = "/Pre-Trip-Checklist"
  to = "/posts/2018/pre-trip-checklist-because-if-i-don-t-write-it-down/"

[[redirects]]
  from = "/Shrimp-Stir-Fry-with-Coconut-Rice"
  to = "/posts/2018/shrimp-stir-fry-with-coconut-rice/"

# 2019 Posts Redirects
[[redirects]]
  from = "/2019-Chicago-Marathon"
  to = "/posts/2019/2019-chicago-marathon-race-review/"

[[redirects]]
  from = "/Assessment-Create"
  to = "/posts/2019/technical-assessment-adding-create-functionality/"

[[redirects]]
  from = "/Assessment-Delete"
  to = "/posts/2019/technical-assessment-adding-delete-functionality/"

[[redirects]]
  from = "/Assessment-Requirements"
  to = "/posts/2019/technical-assessment-requirements-and-first-pass/"

[[redirects]]
  from = "/Assessment-Wrapup"
  to = "/posts/2019/technical-assessment-final-notes/"

[[redirects]]
  from = "/Auth0-Simple-Progressing-Profiling"
  to = "/posts/2019/auth0-progressive-profiling-proof-of-concept/"

[[redirects]]
  from = "/BlueBolt-First-Week"
  to = "/posts/2019/first-week-at-blue-bolt-solutions/"

[[redirects]]
  from = "/No-Easy-Runs"
  to = "/posts/2019/project-bq-no-easy-runs/"

[[redirects]]
  from = "/Project-BQ"
  to = "/posts/2019/project-bq-this-time-for-real/"

[[redirects]]
  from = "/Shopify-Auth0-Multipass"
  to = "/posts/2019/authenticate-shopify-cus  tomers-with-auth0/"

[[redirects]]
  from = "/Shopify-Multipass"
  to = "/posts/2019/shopify-multipass-in-net-core-3-0/"

[[redirects]]
  from = "/TalentLMS-Auth0-SAML"
  to = "/posts/2019/using-saml-2-0-with-auth0-  to-authenticate-users-in-talent-lms/"

# 2020 Posts Redirects
[[redirects]]
  from = "/Another-Year-In-Review"
  to = "/posts/2020/another-year-in-review-2020/"

[[redirects]]
  from = "/Inavord-Architecture"
  to = "/posts/2020/inavord-architecture-a-template-for-success/"

[[redirects]]
  from = "/The-Mandalorian-Season-One"
  to = "/posts/2020/the-mandalorian-season-one-a-few-thoughts/"

[[redirects]]
  from = "/The-Mandalorian-Season-Two"
  to = "/posts/2020/the-mandalorian-season-two-a-few-rants/"

[[redirects]]
  from = "/Twelve-Days-of-Exercisemas"
  to = "/posts/2020/12-days-of-exercisemas/"

# 2021 Posts Redirects
[[redirects]]
  from = "/10000-Words-For-2021/"
  to = "/posts/2021/10-000-words-for-2021/"