backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: https://rovaninet.netlify.app

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{year}}/{{slug}}"
    preview_path: "{{year}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Rovani in C♯", value: "Rovani in C♯" }
          - { label: "Rovani's Vue", value: "Rovani's Vue" }
          - { label: "Rovani Reacts", value: "Rovani Reacts" }
          - { label: "Exactly One Hobby", value: "Exactly One Hobyy" }
          - { label: "Mise-en-Place", value: "Mise-en-Place" }
          - { label: "Vigil Journey", value: "Vigil Journey" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Tags (comma delimited)"
        name: "tags"
        widget: "list"
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
